name: Mani App Engine
on:
  repository_dispatch:
    types: [build_apk]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Dummy APK Structure
        run: |
          mkdir -p output
          echo "Mani, idi nee HTML code: ${{ github.event.client_payload.html_code }}" > output/app_info.txt
          # ఒక డమ్మీ ఫైల్ ని APK పేరుతో క్రియేట్ చేస్తున్నాం టెస్టింగ్ కోసం
          cp output/app_info.txt output/app-debug.apk

      - name: Release APK
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: "Mani Build Success"
          files: output/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
